[package]
name = "plaintext-side-cpa"
version = "0.1.0"
edition = "2021"
authors = ["Prasanna Paithankar <paithankarprasanna@gmail.com>"]

[dependencies]
csv = "1.3.1"
ndarray = "0.16.1"
rayon = "1.10.0"
